### ISSUE TITLE
amazonka-s3-streaming now supports conduit >= 1.3

### ISSUE THREAD

**Issue by axman6** [utdemir/distributed-dataset#12]
It was great to meet you and hear your talk at LambdaJam (I mentioned Ed’s discrimination package). I actually released the update during the conference, so you should now be able to remove the Network.AWS.S3.StreamingUpload.

**Comment by axman6** [comment]
Looks like this is now fixed, thanks!

**Comment by utdemir** [comment]
Yeah, I updated it yesterday and your update worked like a charm, thanks! It'll be even better when your PR to add it on Stackage gets merged.

And thank you for your suggesting discrimination package; I was thinking about implementing sorts, and `discrimination` might work really well for that.

I'm going to take a look at your other issues in the next few days once I get back on track after the conference. Thank you for having a look, I really appreciate it. And please let me know if you have any other issues/opinions/requests or anything else.
