### ISSUE TITLE
Use sourceFileRange from conduit-extra in Control.Distributed.Dataset.LocalTmpShuffleStore.sourceFile

### ISSUE THREAD

**Issue by axman6** [utdemir/distributed-dataset#14]
Using this should avoid the the potentially error prone arithmetic and edge cases involved with handling offsets by hand - http://hackage.haskell.org/package/conduit-extra-1.3.1.1/docs/Data-Conduit-Binary.html#v:sourceHandleRange.

**Comment by utdemir** [comment]
Looks much nicer now, thanks!
